version: 0.2


env:
  shell: bash
  parameter-store:
      DOCKERHUB_USERNAME: /linkbird/dockerhub/username
      DOCKERHUB_ACCESS_TOKEN: /linkbird/dockerhub/access_token
  
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_ACCESS_TOKEN
      - docker build -t linkbird:latest .
      - docker tag linkbird:latest $AWS_ECR_URL/linkbird:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ECR_URL/linkbird:latest