services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - 9292:9292
    env_file:
      - .env
    entrypoint: ./entrypoints/app-entrypoint.sh
    volumes:
      - gem-data:/app/vendor

  worker:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    entrypoint: ./entrypoints/worker-entrypoint.sh

  cron:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    entrypoint: ./entrypoints/cron-entrypoint.sh

  postgres:
    image: postgres:13.1
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:5.0.7
    env_file:
      - .env
    volumes:
      - redis-data:/data



volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  gem-data:
    driver: local
  node-data:
    driver: local