default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: linkbird_dev


test:
  <<: *default
  database: linkbird_test


production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>