default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: twitter_timeline_links_dev


test:
  <<: *default
  database: twitter_timeline_links_test


production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>