default: &default
  url: <%= ENV['DATABASE_URL'] ? ENV['DATABASE_URL'] : 'postgres://localhost:5432/linkbird-dev' %>
  timeout: 5000
  pool: 5
    

development:
  <<: *default

test:
  <<: *default


production:
  <<: *default