---
# Original : Replacement
"cnbc.com" : "https://linkbird-app.s3.amazonaws.com/cnbc.ico"
"nypost.com" : "https://linkbird-app.s3.amazonaws.com/new-york-post.png"
"economist.com" : "https://linkbird-app.s3.amazonaws.com/economist.ico"
"bloomberg.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"washingtonpost.com" : "https://linkbird-app.s3.amazonaws.com/washingtonpost.ico"
"news.bbc.co.uk" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"economist.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"nytimes.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"msnbc.msn.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"cnn.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"abcnews.go.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"wsj.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"time.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"usatoday.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"forbes.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"guardian.co.uk" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"latimes.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"timesonline.co.uk" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"foxnews.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"telegraph.co.uk" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"huffingtonpost.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"npr.org" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"cbsnews.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"csmonitor.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"chicagotribune.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"newsweek.com" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
"slashdot.org" : "https://linkbird-app.s3.amazonaws.com/slashdot.jpg"
"law.cornell.edu" : "https://linkbird-app.s3.amazonaws.com/slashdot.jpg"
