---
# Original : Replacement
"https://news.slashdot.org/favicon.ico" : "https://linkbird-app.s3.amazonaws.com/slashdot.jpg"
"https://www.law.cornell.edu/sites/www.law.cornell.edu/files/favicon_0.ico" : "https://linkbird-app.s3.amazonaws.com/slashdot.jpg"
"https://www.cnbc.com/favicon.ico" : "https://linkbird-app.s3.amazonaws.com/cnbc.ico"
"https://nypost.com/wp-content/themes/nypost-2016/static/images/apple-icons/nypost/apple-icon.png" : "https://linkbird-app.s3.amazonaws.com/new-york-post.png"
"https://www.economist.com/engassets/ico/favicon.f1ea9088.ico" : "https://linkbird-app.s3.amazonaws.com/economist.ico"
"https://www.washingtonpost.com/dr/resources/images/favicon.ico?d=246496593@53d7b042c795d771e0168c17b09aacb0996a3f08" : "https://linkbird-app.s3.amazonaws.com/washingtonpost.ico"
"https://assets.bwbx.io/s3/javelin/public/javelin/images/favicon-black-63fe5249d3.png" : "https://linkbird-app.s3.amazonaws.com/bloomberg.jpg"
